### ISSUE TITLE
Support for csswring

### ISSUE THREAD

**Issue by arabold** [pirxpilot/grunt-mincer#25]
Now that we have nice sourcemap support in `mincer` and `grunt-mincer` (thank you! thank you! thank you!), it would be great to control `csswring` through the `Gruntfile` as well. Specifically I'm looking to use the `preserveHacks` option and I've also noticed that `csswring` appends its own sourcemap comment by default. So when using it with `grunt-mincer` as in the configuration below, 2 comments are generated in every individual CSS file.

```
    // Run Mincer
    mince: {
      main: {
        options: {
          include: ['assets/css/', 'assets/js/'],
          manifestPath: 'public/assets/manifest.json',
          manifestOptions: {
            compress: false,
            sourceMaps: true,
            embedMappingComments: true
          },
          jsCompressor: 'uglify',
          cssCompressor: 'csswring'
        },
        files: [
          {
            src: ['assets/js/*.js', 'assets/js/*.coffee', 'assets/css/*.css', 'assets/css/*.less']
          }
        ]
      },
    },
```

The CSS files have 2 comments whereas only the latter one really is correct (the one which is set via `mincer` and not by `csswring` automatically):
```
body { ... }
/*# sourceMappingURL=style.css.map */
/*# sourceMappingURL=style-fb726407f08d769c56898f726719061c.css.map */
```

**Comment by yabawock** [comment]
closing this as nothing is happening on the mincer side of things to help this along and without configurable csswring options in mincer I can't support it in grunt-mincer.
