### ISSUE TITLE
rc-1 does not obey the 'dist' folder

### ISSUE THREAD

**Issue by ali-bugdayci** [pirxpilot/grunt-mincer#30]
we were using beta4 and it was working fine. 

Now it generates the minced files under the same folder grunt task is run

**Comment by yabawock** [comment]
I think you already reported this as #28 a couple of months ago. If your grunt file hasn't changed between then and now it's probably still the missing path information for the manifest file. Please have a look at the README for the manifestPath option, it clearly states that the destination path in the individual file groups will be ignored when compiling to a manifest.

**Comment by ali-bugdayci** [comment]
wow I totally forgot I reported it before :)

Well my gruntfile mince task options is similar to the README.md one, can you point out where I should change:

```json
  mince: {
      main: {
        options: {
          manifestPath: "manifest.json",
          manifestOptions: {
            compress: false,
            sourceMaps: false,
            embedMappingComments: false
          }
        },
        files: [
          {
            src: ["public/dist/application.min.*"],
            dest: "public/dist/"
          }
        ]
      }
    }
```

**Comment by yabawock** [comment]
Try setting manifestPath to 'public/dist/manifest.json', that should write the resulting files to the correct destination directory.

**Comment by yabawock** [comment]
@ali-bugdayci any status update? Does changing the `manifestPath` option solve this?

**Comment by ali-bugdayci** [comment]
Hi,

I checked it out. Now the files are generated where the manifest path is. It discards the "dest" folder on the files option. 

Is it possible to generate the manifest and assets on different paths? 

ie:
```json
    mince: {
      main: {
        options: {
          manifestPath: "./manifest.json",
          manifestOptions: {
            compress: false,
            sourceMaps: false,
            embedMappingComments: false
          }
        },
        files: [
          {
            src: ["public/dist/application.min.*"],
            dest: "public/dist/"
          }
        ]
      }
    }
```

**Comment by yabawock** [comment]
Sorry, that is not possible at the moment. Writing the manifests and assets with revision information is completely handled by mincer and the assets seems to be always written relative to the manifest.

**Comment by yabawock** [comment]
Closing this as it is not fixable in grunt-mincer
