### ISSUE TITLE
Dependancies out of date

### ISSUE THREAD

**Issue by SimeonC** [pirxpilot/grunt-mincer#31]
Hey, just to let you know - both autoprefixer and mincer have had major updates recently.

Autoprefixer has gone back to the default `autoprefixer` package not `autoprefixer-core`.
Mincer looks like it's changed a lot of stuff as they now use `postcss` instead of `autoprefixer`.

Took me a while to figure that out as I have to go back to `autoprefixer-core@5.2.1`.

**Comment by SimeonC** [comment]
Just adding the warning message I get here:
```
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
```

**Comment by mjonuschat** [comment]
Hi!

`autoprefixer` isn't directly used or referenced by `grunt-autoprefixer`. It's used by the `mincer` module which triggers the warning.

I've updated the dependencies of `grunt-mincer` to allow for `mincer` 1.3+ and the latest sourcemaps support.
